CURRENT_PATIENT_FILE_NAME = "inputPS5a.txt"
NEW_PATIENT_FILE_NAME = "inputPS5b.txt"
CURRENT_PATIENT_OUTPUT_FILE_NAME = "outputPS5.txt"
ALL_PATIENT_OUTPUT_FILE_NAME = "output5.txt"
PATIENT_ID_NUMBER = 1000
